export const Text = [
  "asdf asdf asdf asdf asdf asdf",
  "fdsa fdsa fdsa fdsa fdsa fdsa",
  "asdf fdsa asdf fdsa asdf fdsa",
  "jkl; jkl; jkl; jkl; jkl; jkl;",
  ";lkj ;lkj ;lkj ;lkj ;lkj ;lkj",
  "jkl; ;lkj jkl; ;lkj jkl; ;lkj",
  "gh gh gh gh gh gh gh",
  "hg hg hg hg hg hg hg",
  "gh hg gh hg gh hg gh",
  "asdf jkl; asdf jkl; asdf jkl;",
  "lkj; fdsa lkj; fdsa lkj; fdsa",
  "asdf lkj; fdsa jkl; asdf lkj;",
  "ru ru ru ru ru ru ru",
  "ur ur ur ur ur ur ur",
  "ru ur ru ur ru ur ru",
  "ei ei ei ei ei ei ei",
  "ie ie ie ie ie ie ie",
  "ei ie ei ie ei ie ei",
  "asdf jkl; ruei asdf jkl; ruei",
  "lkj; fdsa ruei lkj; fdsa ruei",
  "asdf lkj; ruei fdsa jkl; ruei",
  "qwer qwer qwer qwer qwer qwer",
  "rewq rewq rewq rewq rewq rewq",
  "qwer rewq qwer rewq qwer rewq",
  "poiuy poiuy poiuy poiuy poiuy poiuy",
  "uyipo uyipo uyipo uyipo uyipo uyipo",
  "poiuy uyipo poiuy uyipo poiuy uyipo",
  "zxcvbnm, zxcvbnm, zxcvbnm, zxcvbnm, zxcvbnm,",
  "mnbvcxz mnbvcxz mnbvcxz mnbvcxz mnbvcxz",
  "zxcvbnm, mnbvcxz zxcvbnm, mnbvcxz zxcvbnm,",
  "bn bn bn bn bn bn bn",
  "nb nb nb nb nb nb nb",
  "bn nb bn nb bn nb bn",
  "zxcv zxcv zxcv zxcv zxcv zxcv",
  "vcxz vcxz vcxz vcxz vcxz vcxz",
  "zxcv vcxz zxcv vcxz zxcv vcxz",
  "bnm, bnm, bnm, bnm, bnm, bnm,",
  "mnb, mnb, mnb, mnb, mnb, mnb,",
  "bnm, mnb, bnm, mnb, bnm, mnb,",
  "fjkl; fjkl; fjkl; fjkl; fjkl; fjkl;",
  "lkj;f lkj;f lkj;f lkj;f lkj;f lkj;f",
  "fjkl; lkj;f fjkl; lkj;f fjkl; lkj;f",
  "asdf vmc asdf vmc asdf vmc asdf vmc",
  "fdsa mvc fdsa mvc fdsa mvc fdsa mvc",
  "asdf vmc fdsa mvc asdf vmc fdsa mvc",
  "asdf tab jkl; asdf tab jkl; asdf tab jkl;",
  "lkj; tab fdsa lkj; tab fdsa lkj; tab fdsa",
  "asdf tab jkl; fdsa tab lkj; asdf tab jkl;",
  "123 123 123 123 123 123",
  "321 321 321 321 321 321",
  "123 321 123 321 123 321",
  "!@# !@# !@# !@# !@# !@#",
  "#@! #@! #@! #@! #@! #@!",
  "!@# #@! !@# #@! !@# #@!",
  "asdf asdf asdf asdf asdf asdf",
  "fdsa fdsa fdsa fdsa fdsa fdsa",
  "asdf fdsa asdf fdsa asdf fdsa",
  "jkl; jkl; jkl; jkl; jkl; jkl;",
  ";lkj ;lkj ;lkj ;lkj ;lkj ;lkj",
  "jkl; ;lkj jkl; ;lkj jkl; ;lkj",
  "gh gh gh gh gh gh gh",
  "hg hg hg hg hg hg hg",
  "gh hg gh hg gh hg gh",
  "asdf jkl; asdf jkl; asdf jkl;",
  "lkj; fdsa lkj; fdsa lkj; fdsa",
  "asdf lkj; fdsa jkl; asdf lkj;",
  "ru ru ru ru ru ru ru",
  "ur ur ur ur ur ur ur",
  "ru ur ru ur ru ur ru",
  "ei ei ei ei ei ei ei",
  "ie ie ie ie ie ie ie",
  "ei ie ei ie ei ie ei",
  "asdf jkl; ruei asdf jkl; ruei",
  "lkj; fdsa ruei lkj; fdsa ruei",
  "asdf lkj; ruei fdsa jkl; ruei",
  "qwer qwer qwer qwer qwer qwer",
  "rewq rewq rewq rewq rewq rewq",
  "qwer rewq qwer rewq qwer rewq",
  "poiuy poiuy poiuy poiuy poiuy poiuy",
  "uyipo uyipo uyipo uyipo uyipo uyipo",
  "poiuy uyipo poiuy uyipo poiuy uyipo",
];
